// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupOldFiles(arg1) {
  return window['go']['main']['App']['CleanupOldFiles'](arg1);
}

export function GetCompanyData(arg1) {
  return window['go']['main']['App']['GetCompanyData'](arg1);
}

export function GetLowStockItems(arg1) {
  return window['go']['main']['App']['GetLowStockItems'](arg1);
}

export function GetProcessedFiles() {
  return window['go']['main']['App']['GetProcessedFiles']();
}

export function ProcessExcelFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessExcelFile'](arg1, arg2);
}

export function UpdateStock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateStock'](arg1, arg2, arg3, arg4);
}
